/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints.index'
import { Route as BlueprintsIdRouteImport } from './routes/blueprints.$id'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as ChannelsIdRouteImport } from './routes/channels.$id'
import { Route as CreatorsIdRouteImport } from './routes/creators.$id'
import { Route as IntegrationsChatgptRouteImport } from './routes/integrations.chatgpt'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicChatgptApproveRouteImport } from './routes/api/public/chatgpt/approve'
import { Route as ApiPublicChatgptBlueprintsRouteImport } from './routes/api/public/chatgpt/blueprints'
import { Route as ApiPublicChatgptChannelsRouteImport } from './routes/api/public/chatgpt/channels'
import { Route as ApiPublicChatgptCreatorsRouteImport } from './routes/api/public/chatgpt/creators'
import { Route as ApiPublicChatgptEstimateRouteImport } from './routes/api/public/chatgpt/estimate'
import { Route as ApiPublicChatgptOpenapiDotjsonRouteImport } from './routes/api/public/chatgpt/openapi[.]json'
import { Route as ApiPublicChatgptPublishRouteImport } from './routes/api/public/chatgpt/publish'
import { Route as ApiPublicChatgptQueueRouteImport } from './routes/api/public/chatgpt/queue'
import { Route as ApiPublicChatgptScansRouteImport } from './routes/api/public/chatgpt/scans'
import { Route as ApiPublicChatgptVideosRouteImport } from './routes/api/public/chatgpt/videos'
import { Route as ApiPublicHooksPublishTickRouteImport } from './routes/api/public/hooks/publish-tick'
import { Route as ApiPublicHooksSyncCronSecretRouteImport } from './routes/api/public/hooks/sync-cron-secret'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube.callback'
import { Route as ApiPublicChatgptChannelsIdRouteImport } from './routes/api/public/chatgpt/channels.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIdRoute = BlueprintsIdRouteImport.update({
  id: '/blueprints/$id',
  path: '/blueprints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIdRoute = ChannelsIdRouteImport.update({
  id: '/channels/$id',
  path: '/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIdRoute = CreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsChatgptRoute = IntegrationsChatgptRouteImport.update({
  id: '/integrations/chatgpt',
  path: '/integrations/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatgptApproveRoute = ApiPublicChatgptApproveRouteImport.update({
  id: '/api/public/chatgpt/approve',
  path: '/api/public/chatgpt/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatgptBlueprintsRoute =
  ApiPublicChatgptBlueprintsRouteImport.update({
    id: '/api/public/chatgpt/blueprints',
    path: '/api/public/chatgpt/blueprints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptChannelsRoute =
  ApiPublicChatgptChannelsRouteImport.update({
    id: '/api/public/chatgpt/channels',
    path: '/api/public/chatgpt/channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptCreatorsRoute =
  ApiPublicChatgptCreatorsRouteImport.update({
    id: '/api/public/chatgpt/creators',
    path: '/api/public/chatgpt/creators',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptEstimateRoute =
  ApiPublicChatgptEstimateRouteImport.update({
    id: '/api/public/chatgpt/estimate',
    path: '/api/public/chatgpt/estimate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptOpenapiDotjsonRoute =
  ApiPublicChatgptOpenapiDotjsonRouteImport.update({
    id: '/api/public/chatgpt/openapi.json',
    path: '/api/public/chatgpt/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptPublishRoute = ApiPublicChatgptPublishRouteImport.update({
  id: '/api/public/chatgpt/publish',
  path: '/api/public/chatgpt/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatgptQueueRoute = ApiPublicChatgptQueueRouteImport.update({
  id: '/api/public/chatgpt/queue',
  path: '/api/public/chatgpt/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatgptScansRoute = ApiPublicChatgptScansRouteImport.update({
  id: '/api/public/chatgpt/scans',
  path: '/api/public/chatgpt/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatgptVideosRoute = ApiPublicChatgptVideosRouteImport.update({
  id: '/api/public/chatgpt/videos',
  path: '/api/public/chatgpt/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishTickRoute =
  ApiPublicHooksPublishTickRouteImport.update({
    id: '/api/public/hooks/publish-tick',
    path: '/api/public/hooks/publish-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCronSecretRoute =
  ApiPublicHooksSyncCronSecretRouteImport.update({
    id: '/api/public/hooks/sync-cron-secret',
    path: '/api/public/hooks/sync-cron-secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatgptChannelsIdRoute =
  ApiPublicChatgptChannelsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicChatgptChannelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/calculator': typeof CalculatorRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/integrations/chatgpt': typeof IntegrationsChatgptRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/chatgpt/approve': typeof ApiPublicChatgptApproveRoute
  '/api/public/chatgpt/blueprints': typeof ApiPublicChatgptBlueprintsRoute
  '/api/public/chatgpt/channels': typeof ApiPublicChatgptChannelsRouteWithChildren
  '/api/public/chatgpt/creators': typeof ApiPublicChatgptCreatorsRoute
  '/api/public/chatgpt/estimate': typeof ApiPublicChatgptEstimateRoute
  '/api/public/chatgpt/openapi.json': typeof ApiPublicChatgptOpenapiDotjsonRoute
  '/api/public/chatgpt/publish': typeof ApiPublicChatgptPublishRoute
  '/api/public/chatgpt/queue': typeof ApiPublicChatgptQueueRoute
  '/api/public/chatgpt/scans': typeof ApiPublicChatgptScansRoute
  '/api/public/chatgpt/videos': typeof ApiPublicChatgptVideosRoute
  '/api/public/hooks/publish-tick': typeof ApiPublicHooksPublishTickRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
  '/api/public/chatgpt/channels/$id': typeof ApiPublicChatgptChannelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/calculator': typeof CalculatorRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/integrations/chatgpt': typeof IntegrationsChatgptRoute
  '/blueprints': typeof BlueprintsIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/chatgpt/approve': typeof ApiPublicChatgptApproveRoute
  '/api/public/chatgpt/blueprints': typeof ApiPublicChatgptBlueprintsRoute
  '/api/public/chatgpt/channels': typeof ApiPublicChatgptChannelsRouteWithChildren
  '/api/public/chatgpt/creators': typeof ApiPublicChatgptCreatorsRoute
  '/api/public/chatgpt/estimate': typeof ApiPublicChatgptEstimateRoute
  '/api/public/chatgpt/openapi.json': typeof ApiPublicChatgptOpenapiDotjsonRoute
  '/api/public/chatgpt/publish': typeof ApiPublicChatgptPublishRoute
  '/api/public/chatgpt/queue': typeof ApiPublicChatgptQueueRoute
  '/api/public/chatgpt/scans': typeof ApiPublicChatgptScansRoute
  '/api/public/chatgpt/videos': typeof ApiPublicChatgptVideosRoute
  '/api/public/hooks/publish-tick': typeof ApiPublicHooksPublishTickRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
  '/api/public/chatgpt/channels/$id': typeof ApiPublicChatgptChannelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/calculator': typeof CalculatorRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/integrations/chatgpt': typeof IntegrationsChatgptRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/chatgpt/approve': typeof ApiPublicChatgptApproveRoute
  '/api/public/chatgpt/blueprints': typeof ApiPublicChatgptBlueprintsRoute
  '/api/public/chatgpt/channels': typeof ApiPublicChatgptChannelsRouteWithChildren
  '/api/public/chatgpt/creators': typeof ApiPublicChatgptCreatorsRoute
  '/api/public/chatgpt/estimate': typeof ApiPublicChatgptEstimateRoute
  '/api/public/chatgpt/openapi.json': typeof ApiPublicChatgptOpenapiDotjsonRoute
  '/api/public/chatgpt/publish': typeof ApiPublicChatgptPublishRoute
  '/api/public/chatgpt/queue': typeof ApiPublicChatgptQueueRoute
  '/api/public/chatgpt/scans': typeof ApiPublicChatgptScansRoute
  '/api/public/chatgpt/videos': typeof ApiPublicChatgptVideosRoute
  '/api/public/hooks/publish-tick': typeof ApiPublicHooksPublishTickRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
  '/api/public/chatgpt/channels/$id': typeof ApiPublicChatgptChannelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brands'
    | '/calculator'
    | '/mcp'
    | '/privacy'
    | '/profile'
    | '/queue'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blueprints/$id'
    | '/channels/$id'
    | '/creators/$id'
    | '/integrations/chatgpt'
    | '/blueprints/'
    | '/channels/'
    | '/.lovable/oauth/consent'
    | '/api/public/chatgpt/approve'
    | '/api/public/chatgpt/blueprints'
    | '/api/public/chatgpt/channels'
    | '/api/public/chatgpt/creators'
    | '/api/public/chatgpt/estimate'
    | '/api/public/chatgpt/openapi.json'
    | '/api/public/chatgpt/publish'
    | '/api/public/chatgpt/queue'
    | '/api/public/chatgpt/scans'
    | '/api/public/chatgpt/videos'
    | '/api/public/hooks/publish-tick'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/youtube/callback'
    | '/api/public/chatgpt/channels/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brands'
    | '/calculator'
    | '/mcp'
    | '/privacy'
    | '/profile'
    | '/queue'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blueprints/$id'
    | '/channels/$id'
    | '/creators/$id'
    | '/integrations/chatgpt'
    | '/blueprints'
    | '/channels'
    | '/.lovable/oauth/consent'
    | '/api/public/chatgpt/approve'
    | '/api/public/chatgpt/blueprints'
    | '/api/public/chatgpt/channels'
    | '/api/public/chatgpt/creators'
    | '/api/public/chatgpt/estimate'
    | '/api/public/chatgpt/openapi.json'
    | '/api/public/chatgpt/publish'
    | '/api/public/chatgpt/queue'
    | '/api/public/chatgpt/scans'
    | '/api/public/chatgpt/videos'
    | '/api/public/hooks/publish-tick'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/youtube/callback'
    | '/api/public/chatgpt/channels/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/brands'
    | '/calculator'
    | '/mcp'
    | '/privacy'
    | '/profile'
    | '/queue'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blueprints/$id'
    | '/channels/$id'
    | '/creators/$id'
    | '/integrations/chatgpt'
    | '/blueprints/'
    | '/channels/'
    | '/.lovable/oauth/consent'
    | '/api/public/chatgpt/approve'
    | '/api/public/chatgpt/blueprints'
    | '/api/public/chatgpt/channels'
    | '/api/public/chatgpt/creators'
    | '/api/public/chatgpt/estimate'
    | '/api/public/chatgpt/openapi.json'
    | '/api/public/chatgpt/publish'
    | '/api/public/chatgpt/queue'
    | '/api/public/chatgpt/scans'
    | '/api/public/chatgpt/videos'
    | '/api/public/hooks/publish-tick'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/youtube/callback'
    | '/api/public/chatgpt/channels/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CalculatorRoute: typeof CalculatorRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRoute
  ScannerRoute: typeof ScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlueprintsIdRoute: typeof BlueprintsIdRoute
  ChannelsIdRoute: typeof ChannelsIdRoute
  CreatorsIdRoute: typeof CreatorsIdRoute
  IntegrationsChatgptRoute: typeof IntegrationsChatgptRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicChatgptApproveRoute: typeof ApiPublicChatgptApproveRoute
  ApiPublicChatgptBlueprintsRoute: typeof ApiPublicChatgptBlueprintsRoute
  ApiPublicChatgptChannelsRoute: typeof ApiPublicChatgptChannelsRouteWithChildren
  ApiPublicChatgptCreatorsRoute: typeof ApiPublicChatgptCreatorsRoute
  ApiPublicChatgptEstimateRoute: typeof ApiPublicChatgptEstimateRoute
  ApiPublicChatgptOpenapiDotjsonRoute: typeof ApiPublicChatgptOpenapiDotjsonRoute
  ApiPublicChatgptPublishRoute: typeof ApiPublicChatgptPublishRoute
  ApiPublicChatgptQueueRoute: typeof ApiPublicChatgptQueueRoute
  ApiPublicChatgptScansRoute: typeof ApiPublicChatgptScansRoute
  ApiPublicChatgptVideosRoute: typeof ApiPublicChatgptVideosRoute
  ApiPublicHooksPublishTickRoute: typeof ApiPublicHooksPublishTickRoute
  ApiPublicHooksSyncCronSecretRoute: typeof ApiPublicHooksSyncCronSecretRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$id': {
      id: '/blueprints/$id'
      path: '/blueprints/$id'
      fullPath: '/blueprints/$id'
      preLoaderRoute: typeof BlueprintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$id': {
      id: '/channels/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof ChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$id': {
      id: '/creators/$id'
      path: '/creators/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof CreatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/chatgpt': {
      id: '/integrations/chatgpt'
      path: '/integrations/chatgpt'
      fullPath: '/integrations/chatgpt'
      preLoaderRoute: typeof IntegrationsChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/approve': {
      id: '/api/public/chatgpt/approve'
      path: '/api/public/chatgpt/approve'
      fullPath: '/api/public/chatgpt/approve'
      preLoaderRoute: typeof ApiPublicChatgptApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/blueprints': {
      id: '/api/public/chatgpt/blueprints'
      path: '/api/public/chatgpt/blueprints'
      fullPath: '/api/public/chatgpt/blueprints'
      preLoaderRoute: typeof ApiPublicChatgptBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/channels': {
      id: '/api/public/chatgpt/channels'
      path: '/api/public/chatgpt/channels'
      fullPath: '/api/public/chatgpt/channels'
      preLoaderRoute: typeof ApiPublicChatgptChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/creators': {
      id: '/api/public/chatgpt/creators'
      path: '/api/public/chatgpt/creators'
      fullPath: '/api/public/chatgpt/creators'
      preLoaderRoute: typeof ApiPublicChatgptCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/estimate': {
      id: '/api/public/chatgpt/estimate'
      path: '/api/public/chatgpt/estimate'
      fullPath: '/api/public/chatgpt/estimate'
      preLoaderRoute: typeof ApiPublicChatgptEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/openapi.json': {
      id: '/api/public/chatgpt/openapi.json'
      path: '/api/public/chatgpt/openapi.json'
      fullPath: '/api/public/chatgpt/openapi.json'
      preLoaderRoute: typeof ApiPublicChatgptOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/publish': {
      id: '/api/public/chatgpt/publish'
      path: '/api/public/chatgpt/publish'
      fullPath: '/api/public/chatgpt/publish'
      preLoaderRoute: typeof ApiPublicChatgptPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/queue': {
      id: '/api/public/chatgpt/queue'
      path: '/api/public/chatgpt/queue'
      fullPath: '/api/public/chatgpt/queue'
      preLoaderRoute: typeof ApiPublicChatgptQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/scans': {
      id: '/api/public/chatgpt/scans'
      path: '/api/public/chatgpt/scans'
      fullPath: '/api/public/chatgpt/scans'
      preLoaderRoute: typeof ApiPublicChatgptScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/videos': {
      id: '/api/public/chatgpt/videos'
      path: '/api/public/chatgpt/videos'
      fullPath: '/api/public/chatgpt/videos'
      preLoaderRoute: typeof ApiPublicChatgptVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-tick': {
      id: '/api/public/hooks/publish-tick'
      path: '/api/public/hooks/publish-tick'
      fullPath: '/api/public/hooks/publish-tick'
      preLoaderRoute: typeof ApiPublicHooksPublishTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-cron-secret': {
      id: '/api/public/hooks/sync-cron-secret'
      path: '/api/public/hooks/sync-cron-secret'
      fullPath: '/api/public/hooks/sync-cron-secret'
      preLoaderRoute: typeof ApiPublicHooksSyncCronSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatgpt/channels/$id': {
      id: '/api/public/chatgpt/channels/$id'
      path: '/$id'
      fullPath: '/api/public/chatgpt/channels/$id'
      preLoaderRoute: typeof ApiPublicChatgptChannelsIdRouteImport
      parentRoute: typeof ApiPublicChatgptChannelsRoute
    }
  }
}

interface ApiPublicChatgptChannelsRouteChildren {
  ApiPublicChatgptChannelsIdRoute: typeof ApiPublicChatgptChannelsIdRoute
}

const ApiPublicChatgptChannelsRouteChildren: ApiPublicChatgptChannelsRouteChildren =
  {
    ApiPublicChatgptChannelsIdRoute: ApiPublicChatgptChannelsIdRoute,
  }

const ApiPublicChatgptChannelsRouteWithChildren =
  ApiPublicChatgptChannelsRoute._addFileChildren(
    ApiPublicChatgptChannelsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CalculatorRoute: CalculatorRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRoute,
  ScannerRoute: ScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlueprintsIdRoute: BlueprintsIdRoute,
  ChannelsIdRoute: ChannelsIdRoute,
  CreatorsIdRoute: CreatorsIdRoute,
  IntegrationsChatgptRoute: IntegrationsChatgptRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicChatgptApproveRoute: ApiPublicChatgptApproveRoute,
  ApiPublicChatgptBlueprintsRoute: ApiPublicChatgptBlueprintsRoute,
  ApiPublicChatgptChannelsRoute: ApiPublicChatgptChannelsRouteWithChildren,
  ApiPublicChatgptCreatorsRoute: ApiPublicChatgptCreatorsRoute,
  ApiPublicChatgptEstimateRoute: ApiPublicChatgptEstimateRoute,
  ApiPublicChatgptOpenapiDotjsonRoute: ApiPublicChatgptOpenapiDotjsonRoute,
  ApiPublicChatgptPublishRoute: ApiPublicChatgptPublishRoute,
  ApiPublicChatgptQueueRoute: ApiPublicChatgptQueueRoute,
  ApiPublicChatgptScansRoute: ApiPublicChatgptScansRoute,
  ApiPublicChatgptVideosRoute: ApiPublicChatgptVideosRoute,
  ApiPublicHooksPublishTickRoute: ApiPublicHooksPublishTickRoute,
  ApiPublicHooksSyncCronSecretRoute: ApiPublicHooksSyncCronSecretRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
