/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints.index'
import { Route as BlueprintsIdRouteImport } from './routes/blueprints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIdRoute = BlueprintsIdRouteImport.update({
  id: '/blueprints/$id',
  path: '/blueprints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/scanner': typeof ScannerRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/blueprints/': typeof BlueprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/scanner': typeof ScannerRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/blueprints': typeof BlueprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/scanner': typeof ScannerRoute
  '/blueprints/$id': typeof BlueprintsIdRoute
  '/blueprints/': typeof BlueprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brands' | '/scanner' | '/blueprints/$id' | '/blueprints/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brands' | '/scanner' | '/blueprints/$id' | '/blueprints'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/scanner'
    | '/blueprints/$id'
    | '/blueprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  ScannerRoute: typeof ScannerRoute
  BlueprintsIdRoute: typeof BlueprintsIdRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$id': {
      id: '/blueprints/$id'
      path: '/blueprints/$id'
      fullPath: '/blueprints/$id'
      preLoaderRoute: typeof BlueprintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  ScannerRoute: ScannerRoute,
  BlueprintsIdRoute: BlueprintsIdRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
